//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either the ZIP file or certificate was not specified!.
        /// </summary>
        internal static string DecryptFilesMissing {
            get {
                return ResourceManager.GetString("DecryptFilesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification decryption process is complete!.
        /// </summary>
        internal static string DecryptionComplete {
            get {
                return ResourceManager.GetString("DecryptionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption Certificate was not specified!.
        /// </summary>
        internal static string EncryptionCertFieldNotFilled {
            get {
                return ResourceManager.GetString("EncryptionCertFieldNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no file found containing the encrypted AES key!.
        /// </summary>
        internal static string MissingAesKeyFile {
            get {
                return ResourceManager.GetString("MissingAesKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no file found containing the encrypted Payload!.
        /// </summary>
        internal static string MissingEncryptedPayload {
            get {
                return ResourceManager.GetString("MissingEncryptedPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary receiver was not specified!.
        /// </summary>
        internal static string SecondaryReceiverFieldNotFilled {
            get {
                return ResourceManager.GetString("SecondaryReceiverFieldNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Signing and Encryption process is complete!.
        /// </summary>
        internal static string SigningAndEncryptionComplete {
            get {
                return ResourceManager.GetString("SigningAndEncryptionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Signing Certificate was not specified!.
        /// </summary>
        internal static string SigningCertFieldNotFilled {
            get {
                return ResourceManager.GetString("SigningCertFieldNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing Certificate password was not specified!.
        /// </summary>
        internal static string SigningCertPasswordFieldNotFilled {
            get {
                return ResourceManager.GetString("SigningCertPasswordFieldNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML file was not specified!.
        /// </summary>
        internal static string XmlFileFieldNotFilled {
            get {
                return ResourceManager.GetString("XmlFileFieldNotFilled", resourceCulture);
            }
        }
    }
}
